### ISSUE TITLE
[Recomendation] Use a git branch rather than shadowing flixel classes

### ISSUE THREAD

**Issue by Geokureli** [TheZoroForce240/FlxPerspective#1]
Hi, It's me, Mr. Haxeflixel!

Cool stuff, here! It's no surprise that you had to hack some flixel classes to get it to work, just wanted to remind you that [shadowing classes](https://github.com/TheZoroForce240/FlxPerspective/tree/main/source/flixel) can lead to many problems down the road. Typically, I recommend making a fork of flixel and creating a specific branch meant to work with your library. This way it's very easy for me understand what changes were needed to facilitate this library, and it's easier merge in future changes to those classes. I also wonder if perhaps you could avoid shadowing FlxCamera by simply extending it.

Lastly if there is some change you need to make to flixel classes that you think would benefit others, feel free to make an issue in the [Flixel github](https://github.com/HaxeFlixel/flixel/issues) about it. I try to stay in-touch with the needs of people using Haxeflixel

**Comment by TheZoroForce240** [comment]
I've reworked a few things and it now just uses some extended classes, might not have been the best way of doing it but it should work for now
